- hosts: kvm_host
  become: true
  tasks:


  - name: Copy kubectl file 
    ansible.builtin.copy:
      src: /ocpinst/kubectl
      dest: /usr/local/bin/kubectl
      remote_src: yes
      owner: root
      group: root
      mode: '0755'

  - name: Copy oc file
    ansible.builtin.copy:
      src: /ocpinst/oc
      dest: /usr/local/bin/oc
      remote_src: yes
      owner: root
      group: root
      mode: '0755'

  - name: Copy openshift-install file
    ansible.builtin.copy:
      src: /ocpinst/openshift-install
      dest: /usr/local/bin/openshift-install
      remote_src: yes
      owner: root
      group: root
      mode: '0755'
      
