- name: add ssh key for wendy
  authorized_key:
    user: wendy
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPnilipwrtw0p+vvpr9dl/nBydqXWgy2j9EKIto3TMe+ ansible"

- name: generate sshd_config file from a template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
